{
	"id": "CVE-2020-15523",
	"description": "In Python 3.6 through 3.6.10, 3.7 through 3.7.8, 3.8 through 3.8.4rc1, and 3.9 through 3.9.0b4 on Windows, a Trojan horse python3.dll might be used in cases where CPython is embedded in a native application. This occurs because python3X.dll may use an invalid search path for python3.dll loading (after Py_SetPath has been used). NOTE: this issue CANNOT occur when using python.exe from a standard (non-embedded) Python installation on Windows.",
	"hardware": [],
	"software": [
		{
			"name": "python2.7",
			"platform": "debian-12",
			"version": "< 0"
		},
		{
			"name": "python2.7",
			"platform": "debian-11",
			"version": "< 0"
		},
		{
			"name": "python2.7",
			"platform": "debian-10",
			"version": "< 0"
		},
		{
			"name": "python2.7",
			"platform": "debian-9",
			"version": "< 0"
		},
		{
			"name": "python2.7",
			"platform": "debian-12",
			"version": "< 0"
		},
		{
			"name": "python2.7",
			"platform": "debian-11",
			"version": "< 0"
		},
		{
			"name": "python2.7",
			"platform": "debian-10",
			"version": "< 0"
		},
		{
			"name": "python2.7",
			"platform": "debian-9",
			"version": "< 0"
		},
		{
			"name": "python2.7",
			"platform": "debian-12",
			"version": "< 0"
		},
		{
			"name": "python2.7",
			"platform": "debian-11",
			"version": "< 0"
		},
		{
			"name": "python2.7",
			"platform": "debian-10",
			"version": "< 0"
		},
		{
			"name": "python2.7",
			"platform": "debian-12",
			"version": "< 0"
		},
		{
			"name": "python2.7",
			"platform": "debian-11",
			"version": "< 0"
		},
		{
			"name": "python2.7",
			"platform": "debian-10",
			"version": "< 0"
		}
	],
	"references": [
		"https://bugs.python.org/issue29778",
		"https://github.com/python/cpython/pull/21297",
		"https://security.netapp.com/advisory/ntap-20210312-0004/"
	],
	"severity": null,
	"state": "published",
	"_is_edited": false
}