{
	"id": "CVE-2021-29617",
	"description": "TensorFlow is an end-to-end open source platform for machine learning. An attacker can cause a denial of service via `CHECK`-fail in `tf.strings.substr` with invalid arguments. The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.\n\nAffected: tensorflow tensorflow < 2.1.4, >= 2.2.0, < 2.2.3, >= 2.3.0, < 2.3.3, >= 2.4.0, < 2.4.2\n\nA security issue has been found in TensorFlow before version 2.4.2. An attacker can cause a denial of service via `CHECK`-fail in `tf.strings.substr` with invalid arguments.",
	"hardware": [],
	"software": [
		{
			"name": "tensorflow",
			"platform": "archlinux",
			"version": "< 2.5.0-1"
		},
		{
			"name": "tensorflow",
			"platform": "archlinux",
			"version": "< 2.5.0-1"
		},
		{
			"name": "tensorflow",
			"platform": "archlinux",
			"version": "< 2.5.0-1"
		},
		{
			"name": "tensorflow",
			"platform": "archlinux",
			"version": "< 2.5.0-1"
		},
		{
			"name": "tensorflow",
			"platform": "archlinux",
			"version": "< 2.5.0-1"
		},
		{
			"name": "tensorflow",
			"platform": "archlinux",
			"version": "< 2.5.0-1"
		}
	],
	"references": [
		"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm",
		"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f",
		"https://github.com/tensorflow/issues/46974",
		"https://github.com/tensorflow/issues/46900"
	],
	"severity": "low",
	"state": "invalid",
	"_is_edited": false
}