{
	"id": "CVE-2020-1738",
	"description": "A flaw was found in Ansible Engine when the module package or service is used and the parameter 'use' is not specified. If a previous task is executed with a malicious user, the module sent can be selected by the attacker using the ansible facts file. All versions in 2.7.x, 2.8.x and 2.9.x branches are believed to be vulnerable.\n\nAffected: Red Hat ansible 2.7.x, 2.8.x, 2.9.x\n\nAffected: Red Hat ansible 2.7.x, 2.8.x, 2.9.x",
	"hardware": [],
	"software": [
		{
			"name": "ansible",
			"platform": "debian-12",
			"version": "*"
		},
		{
			"name": "ansible",
			"platform": "debian-11",
			"version": "*"
		},
		{
			"name": "ansible",
			"platform": "debian-10",
			"version": "*"
		},
		{
			"name": "ansible",
			"platform": "debian-9",
			"version": "*"
		},
		{
			"name": "ansible",
			"platform": "debian-12",
			"version": "*"
		},
		{
			"name": "ansible",
			"platform": "debian-11",
			"version": "*"
		},
		{
			"name": "ansible",
			"platform": "debian-10",
			"version": "*"
		},
		{
			"name": "ansible",
			"platform": "debian-9",
			"version": "*"
		},
		{
			"name": "ansible",
			"platform": "debian-12",
			"version": "*"
		},
		{
			"name": "ansible",
			"platform": "debian-11",
			"version": "*"
		},
		{
			"name": "ansible",
			"platform": "debian-10",
			"version": "*"
		},
		{
			"name": "ansible",
			"platform": "debian-12",
			"version": "*"
		},
		{
			"name": "ansible",
			"platform": "debian-11",
			"version": "*"
		},
		{
			"name": "ansible",
			"platform": "debian-10",
			"version": "*"
		}
	],
	"references": [
		"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1738",
		"https://github.com/ansible/ansible/issues/67796",
		"https://security.gentoo.org/glsa/202006-11"
	],
	"severity": null,
	"state": "invalid",
	"_is_edited": false
}