{
	"id": "CVE-2021-32492",
	"description": "A flaw was found in djvulibre-3.5.28 and earlier. An out of bounds read in function DJVU::DataPool::has_data() via crafted djvu file may lead to application crash and other consequences.\n\nA security issue was found in djvulibre. An out of bounds read in the function DJVU::DataPool::has_data() may lead to an application crash and other consequences via a crafted djvu file.",
	"hardware": [],
	"software": [
		{
			"vendor": "archlinux",
			"product": "djvulibre",
			"version": "< 3.5.28-3"
		},
		{
			"vendor": "debian-bookworm",
			"product": "djvulibre",
			"version": "< 3.5.28-2"
		},
		{
			"vendor": "debian-bullseye",
			"product": "djvulibre",
			"version": "< 3.5.28-2"
		},
		{
			"vendor": "debian-buster",
			"product": "djvulibre",
			"version": "< 3.5.27.1-10+deb10u1"
		},
		{
			"vendor": "debian-stretch",
			"product": "djvulibre",
			"version": "< 3.5.27.1-7+deb9u1"
		}
	],
	"references": [
		"https://bugzilla.redhat.com/show_bug.cgi?id=1943686",
		"https://www.debian.org/security/2021/dsa-5032",
		"https://bugzilla.redhat.com/show_bug.cgi?id=1943410",
		"https://bugzilla.redhat.com/attachment.cgi?id=1770220&action=diff",
		"https://src.fedoraproject.org/rpms/djvulibre/blob/rawhide/f/djvulibre-3.5.27-check-input-pool.patch"
	],
	"_edited_": false,
	"severity": "Medium"
}