{
	"identifier": "CVE-2020-36242",
	"description": "In python-cryptography before version 3.3.2, certain sequences of update calls to symmetrically encrypt multiple gigabytes of data could result in an integer overflow, leading to mishandling of buffers.",
	"type": "network",
	"severity": "critical",
	"state": "published",
	"datetime": "2021-02-07T18:15:00Z",
	"is_edited": false,
	"hardware": [],
	"software": [
		{
			"name": "py3-cryptography",
			"version": "\u003c 3.2.2-r0",
			"architecture": "any",
			"manager": "apk",
			"vendor": "alpinelinux-3.16"
		},
		{
			"name": "py3-cryptography",
			"version": "\u003c 3.2.2-r0",
			"architecture": "any",
			"manager": "apk",
			"vendor": "alpinelinux"
		},
		{
			"name": "py3-cryptography",
			"version": "\u003c 3.2.2-r0",
			"architecture": "any",
			"manager": "apk",
			"vendor": "alpinelinux-3.18"
		},
		{
			"name": "py3-cryptography",
			"version": "\u003c 3.2.2-r0",
			"architecture": "any",
			"manager": "apk",
			"vendor": "alpinelinux-3.17"
		},
		{
			"name": "py3-cryptography",
			"version": "\u003c 3.3.2-r0",
			"architecture": "any",
			"manager": "apk",
			"vendor": "alpinelinux-3.13"
		},
		{
			"name": "python-cryptography",
			"version": "\u003c 3.4-1",
			"architecture": "any",
			"manager": "pacman",
			"vendor": "archlinux"
		},
		{
			"name": "python2-cryptography",
			"version": "\u003c 3.3.2-1",
			"architecture": "any",
			"manager": "pacman",
			"vendor": "archlinux"
		},
		{
			"name": "python-cryptography",
			"version": "\u003c 0:3.3.2-1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-bullseye"
		},
		{
			"name": "python-cryptography",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-buster"
		},
		{
			"name": "python-cryptography",
			"version": "\u003c 3.3.2-1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-sid"
		},
		{
			"name": "python-cryptography",
			"version": "\u003c 3.3.2-1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-trixie"
		},
		{
			"name": "python-cryptography",
			"version": "\u003c 3.3.2-1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-bookworm"
		},
		{
			"name": "python-cryptography",
			"version": "\u003c 3.3.2-1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-bullseye"
		},
		{
			"name": "python-cryptography",
			"version": "\u003c 0:3.3.2-1.",
			"architecture": "any",
			"manager": "apt",
			"vendor": "mariner-1"
		},
		{
			"name": "python3-cryptography",
			"version": "\u003c 0:3.2.1-4.el8",
			"architecture": "armv8",
			"manager": "any",
			"vendor": "redhat-8"
		},
		{
			"name": "python3-cryptography",
			"version": "\u003c 0:3.2.1-4.el8",
			"architecture": "x86_64",
			"manager": "any",
			"vendor": "redhat-8"
		}
	],
	"products": [
		{
			"name": "cryptography",
			"version": "\u003c 3.3.2",
			"architecture": "any",
			"vendor": "cryptography-project",
			"type": "software",
			"is_edited": false,
			"aliases": []
		},
		{
			"name": "fedora",
			"version": "33",
			"architecture": "any",
			"vendor": "fedoraproject",
			"type": "system",
			"is_edited": false,
			"aliases": []
		},
		{
			"name": "communications-cloud-native-core-network-function-cloud-native-environment",
			"version": "1.10.0",
			"architecture": "any",
			"vendor": "oracle",
			"type": "software",
			"is_edited": false,
			"aliases": []
		}
	],
	"references": [
		"https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst",
		"https://github.com/pyca/cryptography/compare/3.3.1...3.3.2",
		"https://github.com/pyca/cryptography/issues/5615",
		"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/L7RGQLK4J5ZQFRLKCHVVG6BKZTUQMG7E/",
		"https://www.oracle.com/security-alerts/cpuapr2022.html",
		"https://www.oracle.com/security-alerts/cpujul2022.html",
		"https://github.com/pyca/cryptography/security/advisories/GHSA-rhm9-p9w5-fwm7",
		"https://github.com/pyca/cryptography/pull/5747",
		"https://github.com/pyca/cryptography/commit/82b6ce28389f0a317bc55ba2091a74b346db7cae",
		"https://access.redhat.com/errata/RHSA-2021:1608",
		"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36242"
	],
	"weaknesses": [
		"CWE-190",
		"CWE-787"
	]
}