{
	"identifier": "CVE-2022-22818",
	"description": "The {% debug %} template tag in Django 2.2 before 2.2.27, 3.2 before 3.2.12, and 4.0 before 4.0.2 does not properly encode the current context. This may lead to XSS.",
	"type": "network",
	"severity": "medium",
	"state": "published",
	"datetime": "2022-02-01T06:00:00Z",
	"is_edited": false,
	"hardware": [],
	"software": [
		{
			"name": "py3-django",
			"version": "\u003c 3.2.12-r0",
			"architecture": "any",
			"manager": "apk",
			"vendor": "alpinelinux"
		},
		{
			"name": "py3-django",
			"version": "\u003c 3.2.12-r0",
			"architecture": "any",
			"manager": "apk",
			"vendor": "alpinelinux-3.17"
		},
		{
			"name": "py3-django",
			"version": "\u003c 3.2.12-r0",
			"architecture": "any",
			"manager": "apk",
			"vendor": "alpinelinux-3.16"
		},
		{
			"name": "python-django",
			"version": "\u003c 4.0.2-1",
			"architecture": "any",
			"manager": "pacman",
			"vendor": "archlinux"
		},
		{
			"name": "python-django",
			"version": "\u003c 2:2.2.28-1~deb11u1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-bullseye"
		},
		{
			"name": "python-django",
			"version": "\u003c 1:1.11.29-1+deb10u4",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-buster"
		},
		{
			"name": "python-django",
			"version": "\u003c 2:3.2.12-1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-sid"
		},
		{
			"name": "python-django",
			"version": "\u003c 2:3.2.12-1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-bookworm"
		},
		{
			"name": "python-django",
			"version": "\u003c 1.6.11-0ubuntu1.3+esm4",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-trusty"
		},
		{
			"name": "python-django",
			"version": "\u003c 1.8.7-1ubuntu5.15+esm4",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-xenial"
		},
		{
			"name": "python-django",
			"version": "\u003c 1:1.11.11-1ubuntu1.16",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-bionic"
		},
		{
			"name": "python-django",
			"version": "\u003c 2:2.2.12-1ubuntu0.10",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-focal"
		},
		{
			"name": "python-django",
			"version": "\u003c 2:2.2.24-1ubuntu1.3",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-impish"
		},
		{
			"name": "python-django",
			"version": "\u003c 2:3.2.12-1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-jammy"
		}
	],
	"products": [
		{
			"name": "django",
			"version": "\u003c 2.2.27",
			"architecture": "any",
			"vendor": "djangoproject",
			"type": "software",
			"is_edited": false,
			"aliases": []
		},
		{
			"name": "django",
			"version": "\u003c 3.2.12",
			"architecture": "any",
			"vendor": "djangoproject",
			"type": "software",
			"is_edited": false,
			"aliases": []
		},
		{
			"name": "django",
			"version": "\u003c 4.0.2",
			"architecture": "any",
			"vendor": "djangoproject",
			"type": "software",
			"is_edited": false,
			"aliases": []
		},
		{
			"name": "fedora",
			"version": "35",
			"architecture": "any",
			"vendor": "fedoraproject",
			"type": "system",
			"is_edited": false,
			"aliases": []
		},
		{
			"name": "debian-linux",
			"version": "11.0",
			"architecture": "any",
			"vendor": "debian",
			"type": "system",
			"is_edited": false,
			"aliases": []
		}
	],
	"references": [
		"https://docs.djangoproject.com/en/4.0/releases/security/",
		"https://groups.google.com/forum/#!forum/django-announce",
		"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/",
		"https://security.netapp.com/advisory/ntap-20220221-0003/",
		"https://www.debian.org/security/2022/dsa-5254",
		"https://www.djangoproject.com/weblog/2022/feb/01/security-releases/",
		"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-22818",
		"https://ubuntu.com/security/notices/USN-5269-1",
		"https://ubuntu.com/security/notices/USN-5269-2"
	],
	"weaknesses": [
		"CWE-79"
	]
}