{
	"identifier": "CVE-2017-5992",
	"description": "Openpyxl 2.4.1 resolves external entities by default, which allows remote attackers to conduct XXE attacks via a crafted .xlsx document.",
	"type": "local",
	"severity": "high",
	"state": "published",
	"datetime": "0000-00-00T00:00:00Z",
	"is_edited": false,
	"hardware": [],
	"software": [
		{
			"name": "python-openpyxl",
			"version": "\u003c 2.4.1-1",
			"architecture": "any",
			"manager": "pacman",
			"vendor": "archlinux"
		},
		{
			"name": "python2-openpyxl",
			"version": "\u003c 2.4.1-1",
			"architecture": "any",
			"manager": "pacman",
			"vendor": "archlinux"
		},
		{
			"name": "openpyxl",
			"version": "\u003c 0:2.3.0-3",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-bullseye"
		},
		{
			"name": "openpyxl",
			"version": "\u003c 0:2.3.0-3",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-buster"
		},
		{
			"name": "openpyxl",
			"version": "\u003c 2.3.0-3",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-bookworm"
		},
		{
			"name": "openpyxl",
			"version": "\u003c 2.3.0-3",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-bullseye"
		},
		{
			"name": "openpyxl",
			"version": "\u003c 2.3.0-3",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-buster"
		},
		{
			"name": "openpyxl",
			"version": "\u003c 2.3.0-3",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-sid"
		},
		{
			"name": "openpyxl",
			"version": "\u003c 2.3.0-3",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-trixie"
		},
		{
			"name": "openpyxl",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-precise"
		},
		{
			"name": "openpyxl",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-trusty"
		},
		{
			"name": "openpyxl",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-xenial"
		},
		{
			"name": "openpyxl",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-yakkety"
		},
		{
			"name": "openpyxl",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-zesty"
		},
		{
			"name": "openpyxl",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-artful"
		},
		{
			"name": "python-openpyxl",
			"version": "\u003c 0:2.3.0-1ubuntu0.1~esm1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-xenial"
		},
		{
			"name": "python3-openpyxl",
			"version": "\u003c 0:2.3.0-1ubuntu0.1~esm1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-xenial"
		}
	],
	"products": [
		{
			"name": "openpyxl",
			"version": "2.4.1",
			"architecture": "any",
			"vendor": "python",
			"type": "software",
			"is_edited": false,
			"aliases": []
		}
	],
	"references": [
		"http://www.openwall.com/lists/oss-security/2017/02/07/5",
		"https://bitbucket.org/openpyxl/openpyxl/commits/3b4905f428e1",
		"https://bitbucket.org/openpyxl/openpyxl/issues/749",
		"https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854442",
		"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-5992",
		"https://ubuntu.com/security/notices/USN-4821-1"
	],
	"weaknesses": [
		"CWE-611"
	]
}