{
	"identifier": "CVE-2023-28859",
	"description": "redis-py before 4.4.4 and 4.5.x before 4.5.4 leaves a connection open after canceling an async Redis command at an inopportune time, and can send response data to the client of an unrelated request. (This could, for example, happen for a non-pipeline operation.) NOTE: the solutions for CVE-2023-28859 address data leakage across AsyncIO connections in general.",
	"type": "none",
	"severity": "medium",
	"state": "published",
	"datetime": "0000-00-00T00:00:00Z",
	"is_edited": false,
	"hardware": [],
	"software": [
		{
			"name": "py3-redis",
			"version": "\u003c 4.5.4-r0",
			"architecture": "any",
			"manager": "apk",
			"vendor": "alpinelinux"
		},
		{
			"name": "py3-redis",
			"version": "\u003c 4.5.4-r0",
			"architecture": "any",
			"manager": "apk",
			"vendor": "alpinelinux-3.18"
		},
		{
			"name": "python-redis",
			"version": "\u003c 4.3.4-3",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-bookworm"
		},
		{
			"name": "python-redis",
			"version": "\u003c 3.5.3-2",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-bullseye"
		},
		{
			"name": "python-redis",
			"version": "\u003c 3.2.1-2",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-buster"
		},
		{
			"name": "python-redis",
			"version": "\u003c 4.3.4-3",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-sid"
		},
		{
			"name": "py39-redis",
			"version": "\u003c 4.5.4",
			"architecture": "any",
			"manager": "any",
			"vendor": "freebsd"
		},
		{
			"name": "python-redis",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-trusty"
		},
		{
			"name": "python-redis",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-xenial"
		},
		{
			"name": "python-redis",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-bionic"
		},
		{
			"name": "python-redis",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-focal"
		},
		{
			"name": "python-redis",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-jammy"
		},
		{
			"name": "python-redis",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-kinetic"
		},
		{
			"name": "python-redis",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-lunar"
		}
	],
	"products": [
		{
			"name": "redis-py",
			"version": "\u003c= 4.5.3",
			"architecture": "any",
			"vendor": "redis",
			"type": "software",
			"is_edited": false,
			"aliases": []
		}
	],
	"references": [
		"https://github.com/redis/redis-py/issues/2665",
		"https://github.com/redis/redis-py/pull/2641",
		"https://github.com/redis/redis-py/pull/2666",
		"https://github.com/redis/redis-py/releases/tag/v4.4.4",
		"https://github.com/redis/redis-py/releases/tag/v4.5.4",
		"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-28859"
	],
	"weaknesses": [
		"CWE-459"
	]
}