{
	"name": "CVE-2011-4137",
	"description": "The verify_exists functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 relies on Python libraries that attempt access to an arbitrary URL with no timeout, which allows remote attackers to cause a denial of service (resource consumption) via a URL associated with (1) a slow response, (2) a completed TCP connection with no application data sent, or (3) a large amount of application data, a related issue to CVE-2011-1521.",
	"packages": [
		{
			"name": "python-django",
			"releases": {
				"bookworm": {
					"status": "resolved",
					"repositories": {
						"bookworm": "2:3.2.13-1"
					},
					"fixed_version": "1.3.1-1",
					"urgency": "not yet assigned"
				},
				"bullseye": {
					"status": "resolved",
					"repositories": {
						"bullseye": "2:2.2.26-1~deb11u1"
					},
					"fixed_version": "1.3.1-1",
					"urgency": "not yet assigned"
				},
				"buster": {
					"status": "resolved",
					"repositories": {
						"buster": "1:1.11.29-1~deb10u1",
						"buster-security": "1:1.11.29-1~deb10u1"
					},
					"fixed_version": "1.3.1-1",
					"urgency": "not yet assigned"
				},
				"sid": {
					"status": "resolved",
					"repositories": {
						"sid": "2:3.2.13-1"
					},
					"fixed_version": "1.3.1-1",
					"urgency": "not yet assigned"
				},
				"stretch": {
					"status": "resolved",
					"repositories": {
						"stretch": "1:1.10.7-2+deb9u9",
						"stretch-security": "1:1.10.7-2+deb9u16"
					},
					"fixed_version": "1.3.1-1",
					"urgency": "not yet assigned"
				}
			}
		}
	],
	"scope": "local"
}