{
	"name": "CVE-2014-3730",
	"description": "The django.util.http.is_safe_url function in Django 1.4 before 1.4.13, 1.5 before 1.5.8, 1.6 before 1.6.5, and 1.7 before 1.7b4 does not properly validate URLs, which allows remote attackers to conduct open redirect attacks via a malformed URL, as demonstrated by \"http:\\\\\\djangoproject.com.\"",
	"packages": [
		{
			"name": "python-django",
			"releases": {
				"bookworm": {
					"status": "resolved",
					"repositories": {
						"bookworm": "2:3.2.13-1"
					},
					"fixed_version": "1.6.5-1",
					"urgency": "not yet assigned"
				},
				"bullseye": {
					"status": "resolved",
					"repositories": {
						"bullseye": "2:2.2.26-1~deb11u1"
					},
					"fixed_version": "1.6.5-1",
					"urgency": "not yet assigned"
				},
				"buster": {
					"status": "resolved",
					"repositories": {
						"buster": "1:1.11.29-1~deb10u1",
						"buster-security": "1:1.11.29-1~deb10u1"
					},
					"fixed_version": "1.6.5-1",
					"urgency": "not yet assigned"
				},
				"sid": {
					"status": "resolved",
					"repositories": {
						"sid": "2:3.2.13-1"
					},
					"fixed_version": "1.6.5-1",
					"urgency": "not yet assigned"
				},
				"stretch": {
					"status": "resolved",
					"repositories": {
						"stretch": "1:1.10.7-2+deb9u9",
						"stretch-security": "1:1.10.7-2+deb9u16"
					},
					"fixed_version": "1.6.5-1",
					"urgency": "not yet assigned"
				}
			}
		}
	],
	"scope": "local"
}